### ISSUE TITLE
Docker Compose volumes

### ISSUE THREAD

**Issue by FrenchBen** [olivere/elastic-with-docker#1]
Using the `volumes` option of the docker-compose.yml creates an error in elasticsearch:

```
elasticsearch_1  | [2016-04-07 04:18:05,521][INFO ][plugins                  ] [Madam Slay] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | Exception in thread "main" java.lang.IllegalStateException: Failed to created node environment
elasticsearch_1  | Likely root cause: java.nio.file.FileSystemException: /usr/share/elasticsearch/data: Function not implemented
elasticsearch_1  |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
elasticsearch_1  |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elasticsearch_1  |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elasticsearch_1  |  at sun.nio.fs.UnixFileStore.readAttributes(UnixFileStore.java:111)
elasticsearch_1  |  at sun.nio.fs.UnixFileStore.getTotalSpace(UnixFileStore.java:118)
elasticsearch_1  |  at org.elasticsearch.env.ESFileStore.getTotalSpace(ESFileStore.java:198)
elasticsearch_1  |  at org.elasticsearch.monitor.fs.FsProbe.getFSInfo(FsProbe.java:59)
elasticsearch_1  |  at org.elasticsearch.env.NodeEnvironment.maybeLogPathDetails(NodeEnvironment.java:269)
elasticsearch_1  |  at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:211)
elasticsearch_1  |  at org.elasticsearch.node.Node.<init>(Node.java:165)
elasticsearch_1  |  at org.elasticsearch.node.Node.<init>(Node.java:140)
elasticsearch_1  |  at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
elasticsearch_1  |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
elasticsearch_1  |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
elasticsearch_1  |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
elasticsearch_1  | Refer to the log for complete error details.
elasticwithdocker_elasticsearch_1 exited with code 1
```

Removing the volume however works great

**Comment by klanghans** [comment]
Thats odd, i have to say on mac OS it works **with** the volumes option, but iam running docker inside docker-machine with parallels

**Comment by olivere** [comment]
Closing due to age.
